In [1]:
#Step1:numpyをインポート
import numpy as np

# Step 2: AとBの行列を格納する多次元配列
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])
B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Step 3: 行列の積の計算
C = np.dot(A, B)

# Step 4: 計算結果を表示
print(C)

# Step 5: 行列の要素の最大値を求める
max_value = np.max(C)
print("最大値:", max_value)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47
